name: hazob_card_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+3

environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.17.0
  gsheets: ^0.4.2
  image_picker: ^0.8.5+3
  flutter_speed_dial: ^6.0.0
  package_info_plus: ^1.4.3
  flutter_secure_storage: ^5.0.2
  googleapis_auth: ^1.3.1
  googleapis: ^8.0.0
  path: ^1.8.1
  file_picker: ^5.0.0


dev_dependencies:
  test: any
  flutter_launcher_icons: ^0.9.3
  lints: ^2.0.0

flutter_icons:
  image_path_android: "assets/img/logoHazob.png"
  image_path_ios: "assets/img/logoHazob.png"
  ios: true
  android: true

flutter:
  uses-material-design: true
  assets:
    - assets/img/
  fonts:
   - family: Montserrat
     fonts: 
        - asset: assets/font/Montserrat-Regular.ttf


